### ISSUE TITLE
'_Token' was not found in request data.

### ISSUE THREAD

**Issue by replay999** [CakeDC/users#1019]
For a new install CakePHP 4.4.10
And add plugin
If I load  $this->loadComponent('FormProtection');
When I try registration, the error appears.

'_Token' was not found in request data.
Cake\Controller\Exception\AuthSecurityException

composer create-project --prefer-dist cakephp/app:~4.0 testcake composer require cakedc/users
Add plugin to applications and uncomment line $this->loadComponent('FormProtection'); from appcontroller

**Comment by rochamarcelo** [comment]
@replay999 which version of the users was installed?

**Comment by replay999** [comment]
Hi @rochamarcelo 
version 11.2

  - Locking cakedc/auth (7.2.0)
  - Locking cakedc/users (11.2.0)
  - Locking cakephp/authentication (2.10.0)
  - Locking cakephp/authorization (2.3.0)

**Comment by rochamarcelo** [comment]
This is happening because the plugin is using Security component.The next version of the plugin for CakePHP 5  is going to use FormProtection.

For now you can use Security component instead of FormProtection or extend the users controller to use FormProtection. Doc to extend the controller: https://github.com/CakeDC/users/blob/11.next-cake4/Docs/Documentation/Extending-the-Plugin.md#extending-the-controller

**Comment by replay999** [comment]
Ok 
Thank
