### ISSUE TITLE
How to migrate this plugin to CakePHP v3.x

### ISSUE THREAD

**Issue by ayman-alkom** [CakeDC/users#216]

**Comment by burzum** [comment]
> How to migrate this plugin to CakePHP v3.x

By changing the code and migrating it!? Fork, change, create pull request.

If you look for a successor of this plugin check this one out, I've basically rewritten this plugin for Cake3. https://github.com/burzum/cakephp-user-tools

**Comment by ayman-alkom** [comment]
You are right, and I hope to be helpful.
But as a programmer I see that things like starting the migration is more likely to be triggered by the project owners.
The contributors can help in fixing bugs, adding features, improving, .... but not start the migration.

**Comment by burzum** [comment]
There hasn't been much activity on the plugins since I left the CakeDC. If you need a Cake3 version urgently you can contact them directly. http://cakedc.com/contact

Or as already proposed try my plugin. The DB schema should match and most of it's API as well. It's just no longer needed to extend any controller or model because everything is now in a component and behavior. Feel free to ask questions or provide feedback, it will help me to improve it in the case there is trouble.

**Comment by ayman-alkom** [comment]
I will try it, very thanks to you
It seems great to not have to extend the user controller

**Comment by steinkel** [comment]
Hi @ayman-alkom we've just released ALPHA version of the 3.x rewrite, feel free to take a look and let us know if you like it :) https://github.com/CakeDC/users/tree/3.x

**Comment by ayman-alkom** [comment]
Hi @steinkel 
It 's very nice to hear that, I will sure try it, thanks a lot
