### ISSUE TITLE
Fatal error: Can't use method return value in write context 

### ISSUE THREAD

**Issue by joserafael** [CakeDC/users#243]
Im my local server with ubuntu 14.04 and php 5.5.x work fine. But in a server production with php 5.4. show this: 
Fatal error: Can't use method return value in write context in /home/joserafa/corefone_evaluaciones/vendor/cakedc/users/src/Controller/Traits/LoginTrait.php on line 86

**Comment by steinkel** [comment]
hi @joserafael and thank you for pointing that out.

It's fixed in the feature/refactor-behavior branch, we are preparing a big merge this week with several improvements done in this branch and also the 3.0.0 release, if you need this now, please use the feature/refactor-behavior meanwhile. Thank you!

**Comment by steinkel** [comment]
Fixing other similar issues with 5.4 now

**Comment by joserafael** [comment]
Thank you, I will try later

**Comment by joserafael** [comment]
Hello steinkel. I installed the branch feature/refactor-behavior and I have the following error: Error: The application is trying to load a file from the CakeDC/Users plugin.

**Comment by steinkel** [comment]
Please use branches:
3.1.x for CakePHP 3.1
3.0.x for CakePHP 3.0
as described in the docs, or let me know if you have issues...

Thank you!
