### ISSUE TITLE
Registration allowed for logged in users

### ISSUE THREAD

**Issue by mferak** [CakeDC/users#330]
I noticed that if I'm logged in, I'm still able to access the Registration page. 

I imagine this should be forbidden, just like it is when I try to access the Login page. 

We don't want a logged in user to be able register another account, do we?

**Comment by mferak** [comment]
If anyone needs a workaround, attached is a solution I ended up using.

Basically I use a custom Users Controller that uses the RegisterTrait, overrides the register function which checks if the users is logged in, and in such case redirects to homepage.

[UsersController.php.txt](https://github.com/CakeDC/users/files/184374/UsersController.php.txt)

**Comment by thinkingmedia** [comment]
Use Gist to share code snippets. It allows for revisions and comments.

https://gist.github.com/thinkingmedia/7dafb8e27ed999440038

**Comment by mferak** [comment]
Thanks, will do next time!

**Comment by thinkingmedia** [comment]
For me, in the past I've erased the current session when the sign in or registration views are shown. This way the forms are shown but if there was a user session it's now closed. Returning to a secure part of the website would redirect to the sign in form.

I think a PR for this kind of behavior would be a benifit.

@steinkel what do you think?

**Comment by steinkel** [comment]
I prefer not to logout the user if they visit the register/login pages, and display a warning message letting them to register a new user or login as another user instead.

**Comment by thinkingmedia** [comment]
If you're building a website for the general public then that would be kind of confusing. Why would someone register someone else.

If you're thinking of an app service then this would be inviting someone. Which isn't the same as registering, or adding a user to a service which again isn't the same as registering.

For me this is purely about app design. On my sign in and registration layouts there is no indication of a user session. For example; when you go to the home page it will show your username in the navigation bar. Where as, the sign in views have no navigation bar (a minimalist design). So there is no indication that a user is currently signed in. That's why I prefer to close the session.

Anyway, this could be done as a configurable option, and 2 lines of code. :smiley:
