### ISSUE TITLE
social accounts view and expiration time

### ISSUE THREAD

**Issue by sasilen** [CakeDC/users#550]
After installation I tried to figure out how would I know who has logged in lately. In the past I have been used to see last_login_time or similar. First thing what came to my mind was this expiration time from social_accounts table.

I found out that my users view missed all related social accounts information as well the token expiration times. I assume that somewhere find is missing `'contain' => ['SocialAccounts']`. Is it missing because of my configuration or bug? Anyways if added that line to SimpleCrudTrait's view function I got that information, not the right place for that I think but I managed to wonder more about these expiration times.

How are these tokens used and what is this `'Token' => ['expiration' => 3600],`. I assumed that every hour token expires and user need to refresh it from eg. google or other other social sources. Still my expiration time is showing date 5/5 even current date is eight and I don't see anything happening to my social account record even If I logout/login. What is purpose of these access tokens?

**Comment by ajibarra** [comment]
Hi @sasilen, actually the users plugin does not use expiration time in any way right now. We leave different applications using users plugin to use and manage the expiration time at their own. This field stores the expiration time coming from the social network so it means when the token won't be valid anymore. 

We don't perform token refresh because from the plugin's point of view it got what it needed (username, email, profile picture, etc) so it does not need to use the token anymore.

That said, It could probably an improvement to implement the refresh token logic. Any contribution is welcomed
