### ISSUE TITLE
Dynamic Roles and Permissions

### ISSUE THREAD

**Issue by marcelonnunes** [CakeDC/users#571]
Where can I find examples and tutorials on **Dynamic** Roles and Permissions (RBAC)?

The Plugin documentation does not contain much detail about Dynamic Roles and Permissions, only **Static** Roles and Permissions.

Thank you.

**Comment by lucasthibau** [comment]
I'm looking for this too...

**Comment by steinkel** [comment]
The plugin provides a static approach based on configuration files to define an RBAC scheme. What do you mean by dynamic? The ability to create new roles and/or modify existing permissions on the fly? I can think of a way to store both the roles and permissions in the database and pull them (similar to another *ancient* plugin I worked on time ago https://github.com/jedt/spark_plug...

**Comment by steinkel** [comment]
Since CakeDC/Auth upgrade you have the ability to define Providers to load permission rules. See https://github.com/CakeDC/auth/blob/master/src/Rbac/Permissions/AbstractProvider.php you would just need to extend this class to retrieve permissions from your database if that's what you are looking for...
