### ISSUE TITLE
The user can not logout.

### ISSUE THREAD

**Issue by walisonbh** [CakeDC/users#584]
Problem encountered in the current master version (5.0.3).

User can not logout.

Correction: Add the logout action in the permissions array of the "_initAuth ()" method of the "UsersAuthComponent" class.

If this is not the case, please let me know what it is.

**Comment by steinkel** [comment]
Hi @walisonbh thank you for reporting this one. Are you using a custom set of rules, this shouldn't be an issue as the default configuration already handles the issue here https://github.com/CakeDC/users/blob/master/config/permissions.php#L68 setting a rule to allow any user to logout action. Please let us know to reopen the issue if needed, thanks.
