### ISSUE TITLE
can not able to create a superadmin user

### ISSUE THREAD

**Issue by jayshris** [CakeDC/users#889]
after bin/cake users addSuperuser

 command getting following issue

"unknown command cake users"

**Comment by steinkel** [comment]
Are you loading the plugin properly into your application?

**Comment by acjbizar** [comment]
I’m experiencing this problem in a fresh CakePHP 5 install. I haven’t had this problem in versions 3 and 4.

I even tried running `bin/cake plugin load CakeDC/Users` after following the installation guide, but that did not fix the problem. Perhaps something changed in the way Cake loads plugins for CLI?

**Comment by steinkel** [comment]
we'll take a look, thank you for reporting it

**Comment by acjbizar** [comment]
> we'll take a look, thank you for reporting it

No problem. Thanks for reopening the issue.

**Comment by steinkel** [comment]
this is what I just did

```
composer create-project 'cakephp/app:5.*' userstest
cd userstest
# change composer.json to add `"minimum-stability": "dev"` at the end
composer require cakedc/users:dev-12.next-cake5
bin/cake plugin load CakeDC/Users
DATABASE_URL=sqlite:///db.sqlite bin/cake migrations migrate -p CakeDC/Users
DATABASE_URL=sqlite:///db.sqlite bin/cake users reset_all_passwords test
```

Final output is

```
➜  userstest DATABASE_URL=sqlite:///db.sqlite bin/cake users reset_all_passwords test
Password changed for all users
New password: test

```

So I don't see a problem with the plugin loading for cake5

Please could you try to reproduce these steps and let us know? Thanks,

**Comment by acjbizar** [comment]
> Please could you try to reproduce these steps and let us know? Thanks,

That worked, thanks! It also made me realize what the problem was. In your example, the command uses underscores (`reset_all_passwords`) whereas what I was trying to do was using camel case (`addSuperuser`).

So, while the feature does work, I actually see two (smaller) problems:

1. [The documentation](https://github.com/CakeDC/users/blob/11.next-cake4/Docs/Documentation/Installation.md) uses the wrong (probably outdated) command `addSuperuser`, which should be `add_superuser`; and
2. The error feedback is somewhat confusing, as it says _Unknown command `cake users`_, but makes no mention of the command that actually fails (which, again, is `addSuperuser`.

**Comment by steinkel** [comment]
documentation has been fixed!

For (2) it might be useful to raise a ticket to cakephp itself, as the error here is not produced by the plugin, thanks!

**Comment by acjbizar** [comment]
Thanks! I will look into that error feedback some more.
